[package]
name = "npuzzle"
version = "0.1.0"
authors = ["no <no@42.fr>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
termion = "1.5.1"

# [dev-dependencies]
# criterion = "0.2.9"

# [[bench]]
# name = "my_benchmark"
# harness = false
